version: "3"

services:
  web-app:
    image: web-app
    ports:
      - "4000:80"
    command: python app.py

  automationtest:
    image: automation-test
    ports:
      - "5904:25900"
      - "4444:24444"
    volumes:
      - .:/home/seluser/automation
    links: #link 之后，可以在容器内部通过服务名字找到web-app,避免使用ip查找
      - web-app
#    depends_on:
#      -

#networks:
#  vpcbr:
#    driver: bridge
#    ipam:
#     config:
#       - subnet: 10.5.0.0/16
#         gateway: 10.5.0.1